### ISSUE TITLE
EntryNotFound error with Node 18.18.0

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode-test-web#104]
1. Use Node 18.18.0
2. Run tests
3. :bug: Tests fail

```
 1) Workspace folder access
       Folder contents:

      AssertionError [ERR_ASSERTION]: Expected values to be strictly deep-equal:
+ actual - expected

+ []
- [ [ '!#$%&\'()+,-.0123456789;=@ABCDEFGHIJKLMNOPQRSTUVWXYZ[]^_`abcdefghijklmnopqrstuvwxyz{}~',
-     1 ] ]
      + expected - actual

      -[]
      +[
      +  [
      +    "!#$%&'()+,-.0123456789;=@ABCDEFGHIJKLMNOPQRSTUVWXYZ[]^_`abcdefghijklmnopqrstuvwxyz{}~"       
      +    1
      +  ]
      +]

        at assertEntries (http://localhost:3000/static/devextensions/dist/web/test/suite/index.js#vscode-extension:25351:16)
        at async Context.eval (http://localhost:3000/static/devextensions/dist/web/test/suite/index.js#vscode-extension:25381:9)

  2) Workspace folder access
       File contents:
     EntryNotFound (FileSystemError): vscode-test-web://mount/folder_with_utf_8_🧿/!%23$%&'()+,-.0123456789;=@ABCDEFGHIJKLMNOPQRSTUVWXYZ[]^_`abcdefghijklmnopqrstuvwxyz{}~
        at MemFileSystemProvider._lookup (http://localhost:3000/static/extensions/fs/dist/fsExtensionMain.js#vscode-extension:149:52)
        at async MemFileSystemProvider._lookupAsFile (http://localhost:3000/static/extensions/fs/dist/fsExtensionMain.js#vscode-extension:167:23)
        at async MemFileSystemProvider.readFile (http://localhost:3000/static/extensions/fs/dist/fsExtensionMain.js#vscode-extension:61:23)
        at async Object.readFile (../../../vs/workbench/api/worker/extensionHostWorker.js:82:25037)      
        at async assertContent (http://localhost:3000/static/devextensions/dist/web/test/suite/index.js#vscode-extension:25354:21)
        at async Context.eval (http://localhost:3000/static/devextensions/dist/web/test/suite/index.js#vscode-extension:25386:9)

  3) Workspace folder access
       File stats:
     EntryNotFound (FileSystemError): vscode-test-web://mount/folder_with_utf_8_🧿/!%23$%&'()+,-.0123456789;=@ABCDEFGHIJKLMNOPQRSTUVWXYZ[]^_`abcdefghijklmnopqrstuvwxyz{}~
        at MemFileSystemProvider._lookup (http://localhost:3000/static/extensions/fs/dist/fsExtensionMain.js#vscode-extension:149:52)
        at async MemFileSystemProvider.stat (http://localhost:3000/static/extensions/fs/dist/fsExtensionMain.js#vscode-extension:49:23)
        at async Object.stat (../../../vs/workbench/api/worker/extensionHostWorker.js:82:24380)
        at async assertStats (http://localhost:3000/static/devextensions/dist/web/test/suite/index.js#vscode-extension:25360:21)
        at async Context.eval (http://localhost:3000/static/devextensions/dist/web/test/suite/index.js#vscode-extension:25395:9)

Error: 3 tests failed.
        at eval (http://localhost:3000/static/devextensions/dist/web/test/suite/index.js#vscode-extension:25508:23)
        at eval (http://localhost:3000/static/devextensions/dist/web/test/suite/index.js#vscode-extension:20613:9)
        at done (http://localhost:3000/static/devextensions/dist/web/test/suite/index.js#vscode-extension:20112:9)
Error running tests: Error: Test failed
    at C:\Users\raymondzhao\work\component-governance\vscode-test-web\out\index.js:59:23
    at async BindingCall.call (C:\Users\raymondzhao\work\component-governance\vscode-test-web\node_modules\playwright-core\lib\client\page.js:634:130)
    at async Page._onBinding (C:\Users\raymondzhao\work\component-governance\vscode-test-web\node_modules\playwright-core\lib\client\page.js:161:7)
error Command failed with exit code 1.
```

**Comment by rzhao271** [comment]
This issue might be fixed with 18.18.1
