### ISSUE TITLE
Tests fail with `Invalid arguments: should be exactly one string.`

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode-test-web#69]
Error: Invalid arguments: should be exactly one string.
    at L.j (http://localhost:3000/static/build/out/vs/workbench/workbench.web.main.js:618:26922)
    at Object.log (http://localhost:3000/static/build/out/vs/workbench/workbench.web.main.js:618:26844)
    at L.warn (http://localhost:3000/static/build/out/vs/workbench/workbench.web.main.js:618:4060)
    at h.warn (http://localhost:3000/static/build/out/vs/workbench/workbench.web.main.js:618:4620)
    at L.warn (http://localhost:3000/static/build/out/vs/workbench/workbench.web.main.js:619:4613)
    at B.Gb (http://localhost:3000/static/build/out/vs/workbench/workbench.web.main.js:2314:65388)
    at async B.Fb (http://localhost:3000/static/build/out/vs/workbench/workbench.web.main.js:2314:65152)

**Comment by aeschli** [comment]
Found on the web:
 * https://chromium.googlesource.com/v8/v8/+/d4ce844be404fbe7532ad422e0540081feb8dfbe/src/inspector/v8-runtime-agent-impl.cc#768
 * https://github.com/microsoft/playwright/issues/12017

Related to
https://github.com/microsoft/vscode-test-web/blob/8e5a70e3847bdc3641f652315baf642e218aad3c/src/index.ts#L190
