### ISSUE TITLE
Unexpected download URL ...vscode-web.tar.gz?1. Should end with .tar.gz

### ISSUE THREAD

**Issue by liweijian** [microsoft/vscode-test-web#80]
I tried to debug the lsp-web-extension-sample with the following commands, but got a weird bug which says `vscode-web.tar.gz?1. Should end with .tar.gz`

```
❯ git remote get-url origin
git@github.com:microsoft/vscode-extension-samples.git

❯ vscode-test-web --browserType=chromium --extensionDevelopmentPath=lsp-web-extension-sample
@vscode/test-web: 0.0.42
unhandledRejection Error: Unexpected download URL: https://vscode.cdn.azure.cn/insider/326dc5a307c54abfa8286da3879f6d8492a3db6a/vscode-web.tar.gz?1. Should end with .tar.gz
    at downloadAndUnzipVSCode (/Users/tli/.volta/tools/image/packages/@vscode/test-web/lib/node_modules/@vscode/test-web/out/server/download.js:60:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async getBuild (/Users/tli/.volta/tools/image/packages/@vscode/test-web/lib/node_modules/@vscode/test-web/out/index.js:84:12)
    at async open (/Users/tli/.volta/tools/image/packages/@vscode/test-web/lib/node_modules/@vscode/test-web/out/index.js:90:16)
uncaughtException Error: read ECONNRESET
    at TLSWrap.onStreamRead (node:internal/stream_base_commons:217:20) {
  errno: -54,
  code: 'ECONNRESET',
  syscall: 'read'
}
```

**Comment by liweijian** [comment]
I commented the related code from ` /Users/tli/.volta/tools/image/packages/@vscode/test-web/lib/node_modules/@vscode/test-web/out/server/download.js` :

```js
async function downloadAndUnzipVSCode(quality, vscodeTestDir) {
    const info = await getLatestVersion(quality);
//    if (!info.url.endsWith('.tar.gz')) {
//        throw new Error(`Unexpected download URL: ${info.url}. Should end with .tar.gz`);
//    }
```

Now it works in a weird way:

```
❯ vscode-test-web --browserType=chromium --extensionDevelopmentPath=lsp-web-extension-sample
@vscode/test-web: 0.0.42
uncaughtException Error: read ECONNRESET
    at TLSWrap.onStreamRead (node:internal/stream_base_commons:217:20) {
  errno: -54,
  code: 'ECONNRESET',
  syscall: 'read'
}
Downloading VS Code Insiders: complete
Extracted to /Users/tli/Downloads/todel/vscode-extension-samples/.vscode-test-web/vscode-web-insider-326dc5a307c54abfa8286da3879f6d8492a3db6a
Serving dev extensions from /Users/tli/Downloads/todel/vscode-extension-samples/lsp-web-extension-sample
Listening on http://localhost:3000
GET /static/devextensions/package.nls.json 404 0.993 ms - 9
GET /static/devextensions/client/dist/browserClientMain.js 404 1.163 ms - 9
```

With error:
<img width="658" alt="image" src="https://user-images.githubusercontent.com/19320783/234755127-bce317b8-0801-4fce-a67b-936472079a94.png">
